name: Java CI / CD with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  PROJECT_NAME: 2020-14f-guys
jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          submodules: recursive

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2.0.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash
      - name: Make zip file
        run: zip -qq -r ./build/libs/*.jar .
        shell: bash
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build/libs/*.jar s3://14f-guys/$PROJECT_NAME/server.zip 
